/**
 * Cloudflare Workers entry for ROJO Y GUALDA (branch `cloudflare`; see docs/CLOUDFLARE_MIGRATION.md).
 *
 * - `fetch`: the unmodified OpenNext handler generated by `opennextjs-cloudflare build` (.open-next/worker.js).
 * - `scheduled`: Cron Triggers replacing the Netlify scheduled functions (netlify/functions/scheduler.mts and
 *   catalog-runner.mts). Jobs are dispatched in-process to the same protected /api/cron/<job> route the Netlify
 *   functions call over HTTP, with the same Bearer CRON_SECRET, so the job code itself is unchanged.
 * - Installs the WASM image codecs that replace sharp on Workers (src/lib/image picks them up at runtime).
 *
 * Bundled by wrangler (not by Next.js), which is what lets it import .wasm modules directly.
 */
import { bindImagesBinding, installImageCodecs } from "./image-codecs";
import { jobsFor } from "./cron";
// @ts-ignore generated by `opennextjs-cloudflare build` (may not exist yet), resolved by wrangler
import openNext from "../.open-next/worker.js";

// Durable Object classes OpenNext may reference (unused by the current config; re-exported so enabling the DO
// queue / sharded tag cache later only needs wrangler.jsonc changes).
// @ts-ignore generated by `opennextjs-cloudflare build` (may not exist yet), resolved by wrangler
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from "../.open-next/worker.js";

installImageCodecs();

interface Env {
  CRON_SECRET?: string;
  [key: string]: unknown;
}
interface Ctx {
  waitUntil(p: Promise<unknown>): void;
  passThroughOnException(): void;
}
interface ScheduledController {
  scheduledTime: number;
  cron: string;
  noRetry(): void;
}
type Handler = { fetch(req: Request, env: Env, ctx: Ctx): Promise<Response> };
const app = openNext as Handler;

async function runJob(job: string, env: Env, ctx: Ctx): Promise<string> {
  // Host is irrelevant for the in-process call; the route only checks the Bearer secret.
  const req = new Request(`https://cron.internal/api/cron/${job}`, { method: "POST", headers: { Authorization: `Bearer ${env.CRON_SECRET ?? ""}` } });
  try {
    const res = await app.fetch(req, env, ctx);
    const body = (await res.text()).slice(0, 300);
    return `${job}:${res.status} ${body}`;
  } catch (e) {
    return `${job}:error ${e instanceof Error ? e.message : String(e)}`;
  }
}

export default {
  fetch(request: Request, env: Env, ctx: Ctx) {
    bindImagesBinding(env.IMAGES);
    return app.fetch(request, env, ctx);
  },

  async scheduled(controller: ScheduledController, env: Env, ctx: Ctx) {
    bindImagesBinding(env.IMAGES);
    if (!env.CRON_SECRET) {
      console.error("[cron] CRON_SECRET is not set; skipping", controller.cron);
      return;
    }
    const jobs = jobsFor(controller.cron, controller.scheduledTime);
    if (!jobs.length) {
      console.warn("[cron] no jobs for", controller.cron);
      return;
    }
    const results = await Promise.allSettled(jobs.map((j) => runJob(j, env, ctx)));
    console.log("[cron]", controller.cron, JSON.stringify(results.map((r) => (r.status === "fulfilled" ? r.value : String(r.reason)))));
  },
};
