/**
 * Product blueprints for the catalog builder: which provider product to use, which colours and
 * sizes to offer, retail prices and the product copy. Provider IDs are resolved (and verified)
 * against the live provider catalogs at build time — the hints below are only starting points.
 */
import type { BlueprintKey, Tone } from "./designs";
import type { RenderMode } from "./render";

export interface Blueprint {
  key: BlueprintKey;
  provider: "printful" | "gelato" | "printify" | "prodigi";
  productType: string;
  category: string;
  label: string; // Spanish product noun used in names
  /** Printful: catalog product IDs to try first; title must match `match`. */
  preferredIds?: string[];
  match: RegExp;
  exclude?: RegExp;
  /** A different provider product for one tone (e.g. black mug for dark designs). */
  alt?: Partial<Record<Tone, { preferredIds?: string[]; match: RegExp; exclude?: RegExp; label?: string }>>;
  placement: string; // provider file type / mockup placement
  renderMode: RenderMode;
  technique: string;
  colors?: Record<Tone, string[]>; // preferred colour names, first available wins (max 3)
  maxColors?: number;
  /** Offer every live (EU) colour of the product that suits the design's tone, preferred colours first. */
  allColors?: boolean;
  sizes?: string[]; // allowed sizes, in display order
  price: number; // base retail price (EUR, VAT incl.)
  sizePremium?: Record<string, number>;
  /** Prodigi: SKUs to try (first existing ones win) and attribute preferences per tone. */
  skus?: { sku: string; label: string }[];
  attrPrefs?: Record<string, Partial<Record<Tone, string[]>> & { any?: string[] }>;
  /** Printify: keep only variants whose option text matches (e.g. recent phone models). */
  variantFilter?: RegExp;
  maxVariants?: number;
  details: string;
  care: string;
}

export const BLUEPRINTS: Record<BlueprintKey, Blueprint> = {
  tee: {
    key: "tee",
    allColors: true,
    provider: "printful",
    productType: "TSHIRT",
    category: "APPAREL",
    label: "Camiseta",
    preferredIds: ["71"],
    match: /3001|Unisex Staple T-Shirt/i,
    exclude: /Youth|Toddler|Baby|Kids|All-Over/i,
    placement: "front",
    renderMode: "print",
    technique: "DTG",
    colors: { dark: ["Black", "Navy", "Black Heather"], light: ["White", "Natural", "Soft Cream", "Heather Dust"] },
    maxColors: 2,
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    price: 29.95,
    sizePremium: { "2XL": 2, "3XL": 4 },
    details:
      "Camiseta unisex de algodón peinado ring-spun 100 % (los colores jaspeados llevan mezcla con poliéster). Tejido ligero y suave, corte regular, costuras laterales y cuello reforzado. Impresión directa sobre la prenda (DTG) con tintas al agua.",
    care: "Lavar del revés en frío. No usar lejía. Secar al aire o en secadora a baja temperatura. Planchar del revés, sin tocar la impresión.",
  },
  kids: {
    key: "kids",
    allColors: true,
    provider: "printful",
    productType: "KIDS_TSHIRT",
    category: "KIDS",
    label: "Camiseta infantil",
    preferredIds: ["732"],
    match: /Youth Classic Tee|Youth.*(Staple )?T-?Shirt|Youth Short Sleeve T-?Shirt/i,
    exclude: /All-Over|Long Sleeve|Tank/i,
    placement: "front",
    renderMode: "print",
    technique: "DTG",
    colors: { dark: ["Black", "Navy"], light: ["White", "Natural", "Soft Cream"] },
    maxColors: 2,
    sizes: ["XS", "S", "M", "L", "XL"],
    price: 22.95,
    details: "Camiseta infantil de algodón suave, corte cómodo y cuello reforzado. Impresión directa (DTG) con tintas al agua, aptas para la piel de los peques.",
    care: "Lavar del revés en frío. No usar lejía. Secar a baja temperatura.",
  },
  hoodie: {
    key: "hoodie",
    allColors: true,
    provider: "printful",
    productType: "HOODIE",
    category: "APPAREL",
    label: "Sudadera con capucha",
    preferredIds: ["146"],
    match: /18500|Unisex Heavy Blend Hoodie/i,
    exclude: /Youth|Zip/i,
    placement: "front",
    renderMode: "print",
    technique: "DTG",
    colors: { dark: ["Black", "Navy", "Dark Heather"], light: ["White", "Sport Grey", "Sand"] },
    maxColors: 2,
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    price: 54.95,
    sizePremium: { "2XL": 3, "3XL": 5 },
    details: "Sudadera unisex de felpa gruesa (50 % algodón, 50 % poliéster), capucha forrada con cordón, bolsillo canguro y puños elásticos. Cálida, resistente y con caída cómoda. Impresión directa (DTG).",
    care: "Lavar del revés en frío con colores similares. No usar lejía. Secar a baja temperatura. No planchar sobre la impresión.",
  },
  sweat: {
    key: "sweat",
    allColors: true,
    provider: "printful",
    productType: "SWEATSHIRT",
    category: "APPAREL",
    label: "Sudadera",
    preferredIds: ["145"],
    match: /18000|Unisex Crew Neck Sweatshirt|Heavy Blend Crewneck/i,
    exclude: /Youth/i,
    placement: "front",
    renderMode: "print",
    technique: "DTG",
    colors: { dark: ["Black", "Navy"], light: ["White", "Sport Grey", "Sand"] },
    maxColors: 2,
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    price: 46.95,
    sizePremium: { "2XL": 3, "3XL": 5 },
    details: "Sudadera de cuello redondo unisex en felpa (50 % algodón, 50 % poliéster), puños y bajo acanalados, interior cepillado. Un básico de entretiempo. Impresión directa (DTG).",
    care: "Lavar del revés en frío. No usar lejía. Secar a baja temperatura. No planchar sobre la impresión.",
  },
  mug: {
    key: "mug",
    provider: "printful",
    productType: "MUG",
    category: "DRINKWARE",
    label: "Taza",
    preferredIds: ["19"],
    match: /White Glossy Mug/i,
    exclude: /Enamel|Travel|Color Inside|Two-Tone/i,
    alt: { dark: { preferredIds: ["300"], match: /Black Glossy Mug/i, exclude: /Enamel|Travel/i } },
    placement: "default",
    renderMode: "mug",
    technique: "SUBLIMATION",
    sizes: ["11 oz", "15 oz"],
    price: 17.95,
    sizePremium: { "15 oz": 3 },
    details: "Taza de cerámica con acabado brillante. El diseño va impreso por ambos lados para que se vea tanto si eres diestro como zurdo. Apta para lavavajillas y microondas.",
    care: "Apta para lavavajillas y microondas.",
  },
  tote: {
    key: "tote",
    allColors: true,
    provider: "printful",
    productType: "TOTE",
    category: "BAGS",
    label: "Bolsa tote",
    preferredIds: ["367", "1553"],
    match: /Cotton Color Tote|Eco Tote Bag|Organic Tote|Tote Bag/i,
    exclude: /All-Over|Large|Beach|Zip|Clear|Denim|Carry-All|AS Colour/i,
    placement: "front",
    renderMode: "print",
    technique: "DTG",
    colors: { dark: ["Black"], light: ["Natural", "Oyster", "White"] },
    maxColors: 2,
    price: 22.95,
    details: "Bolsa tote de algodón resistente con asas largas para llevar al hombro. Perfecta para la compra, la playa o el día a día. Impresión directa (DTG).",
    care: "Lavar a mano o en frío. No usar lejía. Secar al aire.",
  },
  sticker: {
    key: "sticker",
    provider: "printful",
    productType: "STICKER",
    category: "STATIONERY",
    label: "Pegatina",
    preferredIds: ["358"],
    match: /Kiss-Cut Stickers/i,
    exclude: /Sheet|Holographic/i,
    placement: "default",
    renderMode: "sticker",
    technique: "DIGITAL",
    sizes: ["3″×3″", "4″×4″", "5.5″×5.5″"],
    price: 4.95,
    sizePremium: { "4″×4″": 1, "5.5″×5.5″": 2 },
    details: "Pegatina de vinilo resistente con corte a la forma del diseño (kiss-cut) y borde blanco. Para el portátil, la botella, la nevera o la moto.",
    care: "Aplicar sobre superficies limpias y secas. Resistente al agua y a los arañazos del día a día.",
  },
  poster: {
    key: "poster",
    provider: "gelato",
    productType: "POSTER",
    category: "WALL_ART",
    label: "Póster",
    match: /^flat_(300x400|450x600|600x800)-mm/i,
    placement: "default",
    renderMode: "poster",
    technique: "DIGITAL",
    sizes: ["30×40 cm", "45×60 cm", "60×80 cm"],
    price: 24.95,
    sizePremium: { "45×60 cm": 10, "60×80 cm": 20 },
    details: "Póster impreso en papel mate de alta calidad con tintas de larga duración. Colores intensos y negros profundos. Se envía sin marco, enrollado y protegido.",
    care: "Evitar la luz solar directa y la humedad para conservar los colores.",
  },
  framed: {
    key: "framed",
    provider: "prodigi",
    productType: "FRAMED_PRINT",
    category: "WALL_ART",
    label: "Lámina enmarcada",
    match: /.*/,
    skus: [
      { sku: "GLOBAL-CFPM-12X16", label: "30×40 cm" },
      { sku: "GLOBAL-CFPM-18X24", label: "45×60 cm" },
    ],
    attrPrefs: { color: { dark: ["black", "Black"], light: ["white", "White", "natural", "Natural"], any: ["black", "white", "natural"] } },
    placement: "default",
    renderMode: "poster",
    technique: "GICLEE",
    price: 59.95,
    sizePremium: { "45×60 cm": 30 },
    details: "Lámina impresa en papel de calidad museo con tintas pigmentadas, enmarcada a mano con paspartú y protección acrílica. Lista para colgar.",
    care: "Limpiar el marco con un paño seco. Evitar la luz solar directa y la humedad.",
  },
  canvas: {
    key: "canvas",
    provider: "prodigi",
    productType: "CANVAS",
    category: "WALL_ART",
    label: "Lienzo",
    match: /.*/,
    skus: [
      { sku: "GLOBAL-CAN-12X16", label: "30×40 cm" },
      { sku: "GLOBAL-CAN-18X24", label: "45×60 cm" },
    ],
    attrPrefs: { wrap: { dark: ["Black"], light: ["White"], any: ["MirrorWrap", "ImageWrap", "Black", "White"] } },
    maxColors: 1,
    placement: "default",
    renderMode: "fill",
    technique: "GICLEE",
    price: 64.95,
    sizePremium: { "45×60 cm": 30 },
    details: "Lienzo de algodón con acabado mate, tensado sobre bastidor de madera. Colores intensos y duraderos, listo para colgar.",
    care: "Quitar el polvo con un paño suave y seco. Evitar la humedad y el sol directo.",
  },
  towel: {
    key: "towel",
    provider: "printful",
    productType: "BEACH_TOWEL",
    category: "HOME_LIVING",
    label: "Toalla de playa",
    preferredIds: ["259"],
    match: /Beach Towel/i,
    exclude: /Kids|Round|Hooded|Golf|Hand/i,
    placement: "default",
    renderMode: "fill",
    technique: "SUBLIMATION",
    price: 39.95,
    details: "Toalla de playa con cara de microfibra suave estampada por sublimación (colores que no se van con el sol ni el agua) y reverso de algodón absorbente. Para la playa, la piscina o el chiringuito. Fabricada en Europa.",
    care: "Lavar en frío con colores similares. No usar lejía. Secar a baja temperatura.",
  },
  apron: {
    key: "apron",
    allColors: true,
    provider: "printful",
    productType: "APRON",
    category: "HOME_LIVING",
    label: "Delantal",
    preferredIds: ["565"],
    match: /Organic Cotton Apron|Apron/i,
    exclude: /Kids|Child|All-Over|Strap|Embroidered/i,
    placement: "front",
    renderMode: "print",
    technique: "DTG",
    colors: { dark: ["Black", "French Navy", "Navy"], light: ["Natural", "White", "Beige"] },
    maxColors: 2,
    price: 29.95,
    details: "Delantal de algodón orgánico con bolsillo frontal y tiras ajustables. Para la paella del domingo, la barbacoa o la barra del bar. Impresión directa (DTG), fabricado en Europa.",
    care: "Lavar del revés en frío. No usar lejía. Secar al aire.",
  },
  pillow: {
    key: "pillow",
    provider: "printful",
    productType: "PILLOW",
    category: "HOME_LIVING",
    label: "Cojín",
    preferredIds: ["83"],
    match: /All-Over Print Basic Pillow$|Basic Pillow$/i,
    exclude: /Case|Cotton|Shaped/i,
    placement: "front",
    renderMode: "fill",
    technique: "SUBLIMATION",
    maxVariants: 3,
    price: 32.95,
    details: "Cojín de poliéster suave con relleno incluido y cremallera oculta. Estampado por sublimación por ambas caras. Fabricado en Europa.",
    care: "Funda lavable en frío. Relleno: limpiar en seco.",
  },
  bandana: {
    key: "bandana",
    provider: "printful",
    productType: "BANDANA",
    category: "PETS",
    label: "Bandana",
    preferredIds: ["630"],
    match: /All-Over Print Bandana|Bandana/i,
    exclude: /Collar/i,
    placement: "default",
    renderMode: "fill",
    technique: "SUBLIMATION",
    price: 17.95,
    details: "Bandana ligera de poliéster suave en tres tallas (S para gatos y perros pequeños, M y L para perros grandes… o para ti). Estampado por sublimación a todo color. Fabricada en Europa.",
    care: "Lavar a mano en frío. Secar al aire.",
  },
  phonecase: {
    key: "phonecase",
    provider: "printful",
    productType: "PHONE_CASE",
    category: "TECH_ACCESSORIES",
    label: "Funda de móvil",
    preferredIds: ["601"],
    match: /Tough Case for iPhone/i,
    exclude: /MagSafe|Clear|Snap/i,
    variantFilter: /iPhone 1[4-7]/i,
    maxVariants: 16,
    placement: "default",
    renderMode: "fill",
    technique: "DIGITAL",
    price: 26.95,
    details: "Funda resistente de doble capa (policarbonato + TPU) con acabado brillante o mate. Protege de golpes y caídas, deja acceso a botones y es compatible con carga inalámbrica. Fabricada en Europa.",
    care: "Limpiar con un paño húmedo.",
  },
  puzzle: {
    key: "puzzle",
    provider: "printify",
    productType: "PUZZLE",
    category: "HOME_LIVING",
    label: "Puzle",
    match: /Puzzle/i,
    exclude: /Kids|Tin|Magnetic|Wooden/i,
    placement: "front",
    renderMode: "poster",
    technique: "DIGITAL",
    maxVariants: 3,
    price: 34.95,
    details: "Puzle de cartón rígido con acabado brillante, presentado en caja. Un plan para la sobremesa o un regalo con mucho de casa.",
    care: "Guardar en lugar seco.",
  },
  doormat: {
    key: "doormat",
    provider: "printify",
    productType: "DOORMAT",
    category: "HOME_LIVING",
    label: "Felpudo",
    match: /Doormat|Door Mat/i,
    exclude: /Outdoor Rug/i,
    placement: "front",
    renderMode: "fill",
    technique: "SUBLIMATION",
    maxVariants: 2,
    price: 34.95,
    details: "Felpudo de interior con base antideslizante y superficie estampada a todo color. Bienvenida con estilo.",
    care: "Sacudir o aspirar. Limpiar manchas con agua fría.",
  },
  cap: {
    key: "cap",
    allColors: true,
    provider: "printful",
    productType: "CAP",
    category: "HEADWEAR",
    label: "Gorra bordada",
    preferredIds: ["140", "491"],
    match: /Closed-Back Structured Cap|Organic Baseball Cap|Structured Cap/i,
    exclude: /All-Over|Bucket|Trucker|Adidas/i,
    placement: "embroidery_front",
    renderMode: "emb",
    technique: "EMBROIDERY",
    colors: { dark: ["Black", "Navy"], light: ["White", "Khaki"] },
    maxColors: 2,
    price: 27.95,
    details: "Gorra de perfil medio con visera curva, estructurada y de cierre trasero. Diseño bordado en hilo de alta densidad que no se destiñe ni se agrieta. Fabricada en Europa.",
    care: "Limpiar a mano con agua fría y jabón suave. No meter en lavadora ni secadora.",
  },
  beanie: {
    key: "beanie",
    allColors: true,
    provider: "printful",
    productType: "BEANIE",
    category: "HEADWEAR",
    label: "Gorro bordado",
    preferredIds: ["519", "451"],
    match: /Ribbed Knit Beanie|Pom-Pom Beanie|Beanie/i,
    exclude: /All-Over/i,
    placement: "embroidery_front",
    renderMode: "emb",
    technique: "EMBROIDERY",
    colors: { dark: ["Black", "Navy"], light: ["White", "Grey"] },
    maxColors: 2,
    price: 24.95,
    details: "Gorro de punto acanalado, suave y cálido, con doblez y diseño bordado. Para el invierno, el monte o la grada. Fabricado en Europa.",
    care: "Lavar a mano en frío. Secar en plano.",
  },
  embtee: {
    key: "embtee",
    allColors: true,
    provider: "printful",
    productType: "TSHIRT",
    category: "APPAREL",
    label: "Camiseta bordada",
    preferredIds: ["71"],
    match: /3001|Unisex Staple T-Shirt/i,
    exclude: /Youth|Toddler|Baby|Kids|All-Over/i,
    placement: "embroidery_chest_left",
    renderMode: "emb",
    technique: "EMBROIDERY",
    colors: { dark: ["Black", "Navy"], light: ["White", "Natural"] },
    maxColors: 2,
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    price: 34.95,
    sizePremium: { "2XL": 2, "3XL": 4 },
    details: "Camiseta unisex de algodón peinado ring-spun 100 % con el diseño bordado en el pecho, a la altura del corazón. Un básico premium que dura años. Fabricada en Europa.",
    care: "Lavar del revés en frío. No usar lejía. No planchar sobre el bordado.",
  },
  embhoodie: {
    key: "embhoodie",
    allColors: true,
    provider: "printful",
    productType: "HOODIE",
    category: "APPAREL",
    label: "Sudadera bordada",
    preferredIds: ["146"],
    match: /18500|Unisex Heavy Blend Hoodie/i,
    exclude: /Youth|Zip|All-Over/i,
    placement: "embroidery_chest_left",
    renderMode: "emb",
    technique: "EMBROIDERY",
    colors: { dark: ["Black", "Navy"], light: ["White", "Sport Grey"] },
    maxColors: 2,
    sizes: ["S", "M", "L", "XL", "2XL", "3XL"],
    price: 54.95,
    sizePremium: { "2XL": 3, "3XL": 5 },
    details: "Sudadera con capucha de felpa cálida, bolsillo canguro y el diseño bordado en el pecho. Bordado de alta densidad que no se agrieta con los lavados. Fabricada en Europa.",
    care: "Lavar del revés en frío. No usar secadora. No planchar sobre el bordado.",
  },
  patch: {
    key: "patch",
    provider: "printful",
    productType: "PATCH",
    category: "APPAREL",
    label: "Parche bordado",
    preferredIds: ["516"],
    match: /Embroidered Patches/i,
    exclude: /Tactical/i,
    placement: "embroidery_front",
    renderMode: "emb",
    technique: "EMBROIDERY",
    maxVariants: 3,
    price: 9.95,
    details: "Parche bordado con borde remallado y reverso termoadhesivo: plánchalo en chaquetas, mochilas o gorras. Fabricado en Europa.",
    care: "Aplicar con plancha a temperatura alta con un paño protector. Para más resistencia, coser los bordes.",
  },
  glass: {
    key: "glass",
    provider: "printful",
    productType: "GLASS",
    category: "DRINKWARE",
    label: "Vaso de cristal",
    preferredIds: ["653"],
    match: /Shaker Pint Glass/i,
    placement: "default",
    renderMode: "emb",
    technique: "DIGITAL",
    price: 19.95,
    details: "Vaso de cristal tipo pinta (473 ml) con el diseño impreso. Para la caña, el tinto de verano o el vermut del domingo. Fabricado en Europa.",
    care: "Lavar a mano para conservar la impresión.",
  },
  coaster: {
    key: "coaster",
    provider: "printful",
    productType: "COASTER",
    category: "HOME_LIVING",
    label: "Posavasos",
    preferredIds: ["611"],
    match: /Cork-Back Coaster|Coaster/i,
    placement: "default",
    renderMode: "fill",
    technique: "SUBLIMATION",
    price: 9.95,
    details: "Posavasos de superficie brillante con base de corcho antideslizante. Para la mesa del salón o la barra de casa. Fabricado en Europa.",
    care: "Limpiar con un paño húmedo.",
  },
  tumbler: {
    key: "tumbler",
    provider: "printful",
    productType: "TUMBLER",
    category: "DRINKWARE",
    label: "Vaso térmico",
    preferredIds: ["585"],
    match: /Stainless Steel Tumbler/i,
    placement: "default",
    renderMode: "mug",
    technique: "DIGITAL",
    price: 29.95,
    details: "Vaso térmico de acero inoxidable de doble pared con tapa: mantiene el café caliente y el agua fría durante horas. Fabricado en Europa.",
    care: "Lavar a mano. No apto para microondas.",
  },
  flag: {
    key: "flag",
    provider: "printful",
    productType: "FLAG",
    category: "HOME_LIVING",
    label: "Bandera",
    preferredIds: ["490"],
    match: /All-Over Print Flag|Flag/i,
    placement: "default",
    renderMode: "fill",
    technique: "SUBLIMATION",
    price: 34.95,
    details: "Bandera de poliéster con impresión a todo color y ojales metálicos para colgar. Para el balcón, la peña o la grada. Fabricada en Europa.",
    care: "Lavar a mano en frío. Secar a la sombra.",
  },
  postcard: {
    key: "postcard",
    provider: "printful",
    productType: "POSTCARD",
    category: "STATIONERY",
    label: "Postal",
    preferredIds: ["433"],
    match: /Standard Postcard|Postcard/i,
    placement: "default",
    renderMode: "fill",
    technique: "DIGITAL",
    price: 4.95,
    details: "Postal de cartulina gruesa con acabado mate. Para enviar un saludo o enmarcar un recuerdo. Fabricada en Europa.",
    care: "Guardar en lugar seco.",
  },
  calendar: {
    key: "calendar",
    provider: "gelato",
    productType: "CALENDAR",
    category: "STATIONERY",
    label: "Calendario de pared",
    match: /^wall-calendars_pf_a3_.*_ver$/i,
    placement: "default",
    renderMode: "poster",
    technique: "DIGITAL",
    price: 24.95,
    details: "Calendario de pared A3 (29,7 × 42 cm) con espiral metálica y colgador, papel satinado de 250 g. Portada, doce meses con un diseño de la casa cada uno y los festivos nacionales marcados en rojo. Impreso en España.",
    care: "Evitar la luz solar directa y la humedad.",
  },
  blanket: {
    key: "blanket",
    provider: "printify",
    productType: "BLANKET",
    category: "HOME_LIVING",
    label: "Manta",
    match: /Snuggle Blanket|Blanket/i,
    exclude: /Sherpa|Baby|Pet|Weighted|Embroidered/i,
    placement: "front",
    renderMode: "fill",
    technique: "SUBLIMATION",
    maxVariants: 3,
    price: 49.95,
    details: "Manta suave y cálida de forro polar con estampado a todo color por sublimación. Para el sofá, el partido del domingo o las noches de invierno. Fabricada en Europa (Países Bajos).",
    care: "Lavar en frío con colores similares. No usar lejía. Secar a baja temperatura.",
  },
};

/** Map a Gelato poster productUid to a display size. */
export function posterSize(uid: string) {
  if (uid.includes("300x400")) return "30×40 cm";
  if (uid.includes("450x600")) return "45×60 cm";
  if (uid.includes("600x800")) return "60×80 cm";
  return null;
}

/** Normalise Printful size names to our display list ("XXL" → "2XL", 11oz → "11 oz"). */
export function normSize(s: string | null): string | null {
  if (!s) return null;
  const t = s.trim();
  if (/^XXL$/i.test(t)) return "2XL";
  if (/^XXXL$/i.test(t)) return "3XL";
  const oz = t.match(/^(\d+)\s*oz$/i);
  if (oz) return `${oz[1]} oz`;
  const inch = t.replace(/["”]/g, "″").replace(/\s*[x×]\s*/i, "×");
  if (/^\d+(\.\d+)?″×\d+(\.\d+)?″$/.test(inch)) return inch;
  return t;
}

/** Round to a .95 retail price. */
export const retail = (n: number) => Math.max(0.95, Math.ceil(n) - 0.05);
